### ISSUE TITLE
endpoint-in-domain validation improvment

### ISSUE THREAD

**Issue by rhoerbe** [Emergya/peer#32]
Uploading and EntityDescriptor results in this error message:

    The endpoint at https://testshib.portalverbund.at:8443/idp/profile/SAML2/SOAP/ArtifactResolution does not belong to the domain portalverbund.at

but it should read:

    "The FQHN of endpoint https://testshib.portalverbund.at:8443/idp/profile/SAML2/SOAP/ArtifactResolution is not equal to the domain portalverbund.at"

I think that it would make fore sense require the endpoint address to be part of the domain instead, so host.example.com must be in example.com. To achieve this, entity/validation.py from line 100 on should be changed to:

            if not url.hostname.lower().endswith(domain.lower()):
                errors.append(
                    u'The FQHN of endpoint %s is not in the domain %s' %
                    (endpoint['Location'], domain))

**Comment by yghorbal** [comment]
:+1: 

I’m trying to setup a peer instance to manage internal SPs inside my organisation. It’s up and running, even though the python package documentation is quit old, but knowning Django, we managed to make it work. Now, I’m hit by this very issue :(
Basically all our SPs have entity names with subdomains (of a unique single domain) :
- https://app1.pasteur.fr/
- https://app2.pasteur.fr/
[…]

The domain check is strict on the exact chain. It works if I add app1.pasteur.fr as a domain but it’s quiet a hassel to add a domain for each entity…

It could be nice if :
- make the domain check optional application wide. That can suite internal instances where only “admins” manage Entitys (that will be our case)
- make the domain check more loose so it catches the subdomain (or even make this loosness optional and up to the deployer to activate it at his own risk)

**Comment by enriquepablo** [comment]
I think validation of subdomains in entities' endpoints should use the same logic as that for domains in [1]. In [1], a domain is validated straight away if there is a validated superdomain with the same owner. So, if an owner has a validated domain, she will always be able to add an entity with endpoints in a subdomain of that (even if she has to go about creating a new domain verified as a subdomain of the original domain).

See commit referenced in previous comment.

https://github.com/Emergya/peer/blob/master/peer/domain/validation.py#L138
