### ISSUE TITLE
Add support to the complete mdUI schema

### ISSUE THREAD

**Issue by ablanco** [Emergya/peer#36]
SAMLMetaJS doesn't currently support the whole mdui schema.

E.g. some nodes get lost in the *DiscoHint* section because SAMLMetaJS doesn't support them. I'm talking about *DomainHint* and *IPHint*. What SAMLMetaJS doesn't support doesn't get to its internal representation, and therefore, it doesn't appear in the generated XML.

**Comment by enriquepablo** [comment]
Not applicable with the new editor
