### ISSUE TITLE
Explicit warning if elements of an EntityDescriptor are not in the schema

### ISSUE THREAD

**Issue by rhoerbe** [Emergya/peer#37]
If a user uploads Metadata and parts of it cannot be understood, PEER should ask the user to confirm if processing may continue. It would be helpful to explain which parts of the XML cannot be understood.

**Comment by enriquepablo** [comment]
The new metadata editor respects the xml chunks it doesn't understand.

**Comment by rhoerbe** [comment]
Is the issue implemented completely, i.e. does the editor flag contents it does not recognize?

**Comment by enriquepablo** [comment]
There are 2 cases I think. If the js editor does not understand an xml chunk, it will respect it (keep it), and show it on a special box of unparsed xml (so yes, it will "flag" those contents). Then, in the server, either lxml validates the whole md doc against the [schema](https://github.com/Emergya/peer/blob/master/peer/entity/schema/schema.xsd), in which case there will be no errors or warnings, or it doesn't, in which case the parsing errors will be shown all together above the editor.

The problem of showing backend parsing errors in the frontend right next to the problematic elements as they are parsed in the frontend, is that they are 2 different parsers (they have to be). In the backend the parser is generic, lxml plus an xsd, but in the frontend it is specific for saml md. So elements that produce errors in the backend may not even exist in the internal representation of the frontend; There isn't a common representation of the md doc that can be used as a reference to locate backend messages. The only way I see to do this is ad hoc for each possible kind of parsing error...

If you feel this is not satisfactory, feel free to reopen the issue, no need to tell you :)

**Comment by rhoerbe** [comment]
I see. Anyway, I did not expect validation errors to show up in context. But assuming that the current validation is considered minimal, any other back-end validation rules should not hurt, because these rules, if violated, would show up at save time.
