### ISSUE TITLE
FO workflow in peer

### ISSUE THREAD

**Issue by rhoerbe** [Emergya/peer#46]
In addition to use PEER as a self-registration service for SPs and IdPs I would like to deploy it as an FO admin tool. The additional functionality required by the FO is
a) a link from the domain to an LDAP listing eligible organizations (or the ldap imported into PG), 
b) a simple workflow to manually confirm new, changed and revoked EDs,
c) a method to mark revoked EDs for pyFF to exclude the ED from further processing.

Would that functionality be in line with PEERs goals? I would rather prefer to submit additions than make a fork.

**Comment by enriquepablo** [comment]
b) and c) are already covered, specially since merging the workflow work from the people from GRNET.

IIUC, at the moment (a) would just need a validator that checks each new domain or ED against the list of eligible domains, right?

**Comment by rhoerbe** [comment]
Requirement (a) has been overtaken by other developments. In the AT government use case we use an extra privilege management system to sign EDs. So selecting organizations from an LDAP is not required any more.
