### ISSUE TITLE
Default rendering of entity does not return DisplayName for IDP

### ISSUE THREAD

**Issue by rhoerbe** [Emergya/peer#52]
In a list of entities that all have English and German mdui:DisplayName elements, IDPs do not show DisplayName in the listof entities.
If I test for the element (/md:EntityDescriptor/md:IDPSSODescriptor/md:Extensions/mdui:UIInfo/mdui:DisplayName), it shows the proper result:
```
<mdui:DisplayName xmlns:mdui="urn:oasis:names:tc:SAML:metadata:ui" xml:lang="de">Test Driver IdP</mdui:DisplayName> 
<mdui:DisplayName xmlns:mdui="urn:oasis:names:tc:SAML:metadata:ui" xml:lang="en">Test Driver IdP</mdui:DisplayName>
```
Looking into the unicode() method in the entity model I cannot see that the type of SSODescriptor would make a difference.

**Comment by enriquepablo** [comment]
This is overcome by the new listings of entities (from the admin app), that can be configured to show any columns.
