### ISSUE TITLE
subdomains

### ISSUE THREAD

**Issue by skoranda** [Emergya/peer#54]
I have proved that I control the domain 'ligo.org'. The LIGO project has many SPs that I would like to register such as ask.ligo.org, wiki.ligo.org, gracedb.ligo.org, dcc.ligo.org, and so on. It would be helpful if I could publish metadata for those SPs served from *.ligo.org without having to prove I control each one.

**Comment by enriquepablo** [comment]
This would be fixed with https://github.com/Emergya/peer/compare/entity-subdomain-validation?expand=1

Closing this as duplicate of #32
