### ISSUE TITLE
UI Improvement: Start screen clean-up

### ISSUE THREAD

**Issue by rhoerbe** [Emergya/peer#58]
In general a start screen should offer the most frequently used options and data items, and contain only items that are necessary for the user.

Recommendation 1: For an unauthenticated user, the start screen should only show:
* The (small) PEER logo
* The „Sign in“ button (sign up should be moved to the sign-in page – see the Google authenticator that implements this nicely)
* A slogan that catches the purpose of the service
* A link to a short explanation of the application („Who can do what?“)
* General terms
Remove the banner image completely (little information, takes lot of screen space)
Remove the „latest Entity“ list, as this is not useful in most cases.

Recommendation 2: For an authenticated user, the start screen should only show:
* The items for the unauthenticated user (except user name instead of „sign in“)
* The navigation menu at the canonical location, which is the left sidebar
* A list of data items should depend on the role of the user:
** A list of own entities of entity operators (with sort and filter capabilities for Leo' user story)
** Recently added domains and entities for the MD registrar

Remark: This issue is based on the PEER user stories in http://files.hoerbe.at/permalink/PEER_UI_Considerations.pdf

**Comment by leifj** [comment]
concur

**Comment by enriquepablo** [comment]
This is done
