### ISSUE TITLE
UI Improvement: Locating an entity

### ISSUE THREAD

**Issue by rhoerbe** [Emergya/peer#59]
Searching and filtering entities should be possible using their most common attributes, like domain, mdui names, organization and contact.

Recommendation 3: 
* The entities list should be separated from the list of domains, having separate menu entries in the navigation menu)
* In addition to storing metadata in Git, a subset of the EntityDescriptor should stored in the database. Separate fields should be used to enable filtering. At least following fields should be available: domain, mdui:description, organizationName, entityAttribute, RoleDescriptor (IDP, SP or both). It will be necessary to define a preferred and a fallback language for this purpose.
* A simple, single-line table format would be helpful, particularly if combined with a dynamic display table that would allow users to sort and adapt columns (like django-tables2)
* Fluid layout would help to show more columns per line. Currently wide screens do not help because of the fixed width. 

Remark: This issue is based on the PEER user stories in http://files.hoerbe.at/permalink/PEER_UI_Considerations.pdf

**Comment by enriquepablo** [comment]
This is done
