### ISSUE TITLE
UI Improvement: Navigating through CRUD functions

### ISSUE THREAD

**Issue by rhoerbe** [Emergya/peer#60]
Users should be able to use a continuous navigation to browse, display details and add/update/delete entities (and other data). There are several established practices for this; one I consider a best practice is:
* In the list view (not allowing multiple records to be selected) there are only 4 functions:
** Add
** Display detail (a link on the first column)
** Filter (options in the right sidebar)
** Search (search box on top of the list)
* The display view offers:
** Add
** Modify
** Delete
** Back to list
* The add/Modify/Delete forms allow the user to commit or cancel. Cancel will go back to the display form.

Recommendation 4: Implement a navigation allowing the user to drill down from a condensed list format with search/filter/browse functions to a detailed display, from where add/update/delete are available. Each screen should have a back button to arrive at the previous page.

Remark: This issue is based on the PEER user stories in http://files.hoerbe.at/permalink/PEER_UI_Considerations.pdf

**Comment by enriquepablo** [comment]
This is done
