### ISSUE TITLE
UI Improvement: Editing an EntityDescriptor

### ISSUE THREAD

**Issue by rhoerbe** [Emergya/peer#61]
The edit form should approach the other forms in look and feel.

Recommendation 5: The Display, Add and Modify forms should have a consistent layout. 

Recommendation 6: Validation in the front-end and backend should be identical. The Javascript Editor should use call-backs to Django for this purpose. (see issue #55 on Github).

Recommendation 7: Use a fluid layout and align it with the Django app. Ideally a stylesheet would be factored out from Django and the Javascript editor to maintain common CSS.

Remark: This issue is based on the PEER user stories in http://files.hoerbe.at/permalink/PEER_UI_Considerations.pdf

**Comment by enriquepablo** [comment]
All this has been addressed elsewhere
