### ISSUE TITLE
UI-glitch during sigh-up with username format

### ISSUE THREAD

**Issue by rhoerbe** [Emergya/peer#63]
The username field on the sign-up page does not allow a dot in the name (should't it allow an rfc822-name/email address?)

The glitch is, that there is neither an indication which field is the cause, nor what the allowed values for the userid field are.

Fix: indicate the field in error, and make the message specific to the real cause ("field in error is not good enough").

**Comment by albluqmun** [comment]
Hi @rhoerbe,

The username field actually allows a dot. I attach two images. In the first image you can see the error message with the characters allowed. In the another image, I have a username with a dot, and the form validation allows that field.

First image:
![wrong_username](https://cloud.githubusercontent.com/assets/10974767/10161718/4930551a-66a6-11e5-852c-b999fed298ae.jpg)
Second image:
![valid_username](https://cloud.githubusercontent.com/assets/10974767/10161725/4eec09ea-66a6-11e5-961b-0209aece8f7f.jpg)
