### ISSUE TITLE
Domain validation issues

### ISSUE THREAD

**Issue by jkakavas** [Emergya/peer#66]
Hi, 
The domain validation is currently performed with the help of the whois python module. 
```
 whois.whois(domain)
```
I see two problems with this : 
1) The problem is that some TLDs do not have a whois server so this fails for all domains. .gr is the one that affects us but, for example, .es does not have a whois server either.
2) For TLDs that have a whois server, the whois.whois(domain) does not fail with an exception when the domain is not found, it just returns a dict with None values. This causes a TypeError 
```
Traceback:
File "/home/ikakavas/.virtualenvs/peer/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/ikakavas/.virtualenvs/peer/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  22.                 return view_func(request, *args, **kwargs)
File "/home/ikakavas/code/peer/peer/domain/views.py" in domain_verify
  130.     domain_contact_list = get_administrative_emails_from_whois(domain.name)
File "/home/ikakavas/code/peer/peer/domain/utils.py" in get_administrative_emails_from_whois
  128.         administrative_emails = list(set(administrative_emails))

Exception Type: TypeError at /domain/2
Exception Value: 'NoneType' object is not iterable
```
even though the domain is actually added.

**Comment by enriquepablo** [comment]
At the moment, the TypoeError is gone, and in case the tld has no whois server, whois validation is skipped. Is this ok?

**Comment by jkakavas** [comment]
If the whois validation is skipped, then how will you get domain_contact_list , administrative_emails, etc ? Will there be another flow to validate the domain ?

**Comment by enriquepablo** [comment]
Perhaps skipped is not the word. [whois.whois(str(value))](https://github.com/Emergya/peer/blob/master/peer/domain/validation.py#L176) does not produce an exception if the domain has no whois server, so validation succeeds. The domain contact list etc is obtained just the same as before, but with no TypeError.

**Comment by jkakavas** [comment]
Thanks, now I got it.
