### ISSUE TITLE
Domainname check in entity validation fails if URL has explicit port

### ISSUE THREAD

**Issue by rhoerbe** [Emergya/peer#70]
This fails:

    <md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
                                 Location="https://osxdevl.hoerbe.at:8088/slo/post"/>

This works:

    <md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
                                 Location="https://osxdevl.hoerbe.at/slo/post"/>

**Comment by enriquepablo** [comment]
fixed
