### ISSUE TITLE
Endpoint URL in FQDN validation problem

### ISSUE THREAD

**Issue by rhoerbe** [Emergya/peer#78]
When adding this entity http://files.hoerbe.at/daunlod/idpExampleOrg.xml to domain example.org, I am  receiving error messages "The entityid does not belong to the domain example.org", "The endpoint at https://idp.example.org/idp/profile/SAML2/POST/SSO does not belong to the domain example.org" and "The endpoint at https://idp.example.org/idp/profile/SAML2/Redirect/SSO does not belong to the domain example.org"

**Comment by enriquepablo** [comment]
This has been addressed in https://github.com/Emergya/peer/pull/56
