### ISSUE TITLE
Add forms still overwrite navigation menu

### ISSUE THREAD

**Issue by rhoerbe** [Emergya/peer#89]
According to the UI improvement recommendations that navigation menu should be static. However, add domain, add entity, add entity group and the (empty!) help page overwrite the nav menu column.

**Comment by rhoerbe** [comment]
OIther forms suffer from the same issue, like the "domain created" page. The navigation menu should be a fundamental part of the application, such as tied in a high-level template or other framework component. Otherwise it has to be added to each page, where it can be easily "forgotten".
The developer should think of the typical CMS-type layout, where general navigation is not a concern of each content frame, but provided on an outer level.

**Comment by enriquepablo** [comment]
I have made the main navigation menu universal, and have added a secondary menu to the entity pages with entity specific actions.

**Comment by enriquepablo** [comment]
The layout of many pages broke with the universal nav menu, I think it is fixed now.
