### ISSUE TITLE
Domainname validation fails

### ISSUE THREAD

**Issue by rhoerbe** [Emergya/peer#96]
Adding metadata to the entity with id=10 from http://pastebin.com/jj0K2kCp fails:

The metadata is not valid!

Please correct the errors indicated below

The endpoint at https://v-portal.tirol.gv.at/IdPWeb/profile/SAML2/POST/SSO does not belong to the domain v-portal.tirol.gv.at or to any of its subdomains.
The endpoint at https://v-portal.tirol.gv.at/IdPWeb/profile/SAML2/Redirect/SSO does not belong to the domain v-portal.tirol.gv.at or to any of its subdomains.
The entityid does not belong to the domain v-portal.tirol.gv.at or to any of its subdomains.

**Comment by enriquepablo** [comment]
I've just copypasted the referenced metadata from pastebin and added it to the entity with id=10, with no complain.
